name: apphomefisio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- PACOTES ESSENCIAIS ---
  fl_chart: ^0.68.0           # Para os gráficos
  http: ^1.2.1                # Para enviar dados ao Flask
  path_provider: ^2.1.3       # Para encontrar onde salvar o CSV
  share_plus: ^9.0.0          # Para abrir o menu "Compartilhar"
  shared_preferences: ^2.2.3  # Para o Login/Cadastro funcionar
  google_fonts: ^6.2.1        # <--- ESTAVA FALTANDO ESSE AQUI
  lottie: ^2.4.0              # Para animações

  cupertino_icons: ^1.0.8
  video_player: ^2.6.1
  chewie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.jpeg
    - assets/streak_done.gif
    - assets/graf.gif
    - assets/videos/
    - assets/doctor.json

# Configuração para gerar os ícones do app (Android / iOS)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"

# Configuração para gerar a splash nativa com a mesma imagem
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.jpeg
  android: true
  ios: true
  web: false